services:
  backend:
    build:
      context: .
      dockerfile: services/backend/Dockerfile
    env_file: .env
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--enable-source-maps
    command: ["node", "--loader", "ts-node/esm", "services/backend/src/main.ts"]
    ports:
      - "8080:8080"
    depends_on:
      - valkey
    healthcheck:
      test: ["CMD", "node", "services/backend/scripts/healthcheck.mjs"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  valkey:
    image: valkey/valkey:7
    ports:
      - "6379:6379"
    restart: unless-stopped
