name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Renovate config
        run: make renovate-validate
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Install dependencies
        run: make install
      - name: Enforce Dependency Constraints
        run: make constraints
      - name: Lint Source Code
        run: make lint
      - name: Type Check
        run: make typecheck
      - name: Check Code Formatting
        run: make format-check

  build-artifacts:
    name: Build Artifacts
    runs-on: ubuntu-latest
    needs: [code-quality]
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Install dependencies
        run: make install
      - name: Build All Workspaces
        run: make build

  test-and-coverage:
    name: Run Tests & Collect Coverage
    runs-on: ubuntu-latest
    needs: [code-quality]
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Install dependencies
        run: make install
      - name: Test and Generate Coverage Report
        run: make coverage-ci
      - name: Comment coverage on PR (find existing)
        if: ${{ github.event_name == 'pull_request' }}
        id: find-coverage-comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: github-actions[bot]
          body-includes: "coverage-summary: do not edit"
      - name: Comment coverage on PR (create or update)
        if: ${{ github.event_name == 'pull_request' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find-coverage-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: coverage-summary.md
          edit-mode: replace
      - name: Upload backend coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-backend
          path: services/backend/coverage
          if-no-files-found: warn
      - name: Upload types coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-types
          path: packages/types/coverage
          if-no-files-found: warn
