name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-quality:
    name: Code Quality Checks
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Renovate config
        run: make renovate-validate
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Install dependencies
        run: make install
      - name: Enforce Dependency Constraints
        run: make constraints
      - name: Lint Source Code
        run: make lint
      - name: Type Check
        run: make typecheck
      - name: Check Code Formatting
        run: make format-check

  build-artifacts:
    name: Build Artifacts
    runs-on: ubuntu-latest
    needs: [code-quality]
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Install dependencies
        run: make install
      - name: Build All Workspaces
        run: make build

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [code-quality]
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Install dependencies
        run: make install
      - name: Run tests (with coverage)
        run: make coverage
      - name: Report Backend Coverage
        if: ${{ always() && github.event_name == 'pull_request' }}
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          name: Backend
          working-directory: services/backend
          file-coverage-mode: changes
      - name: Report Types Coverage
        if: ${{ always() && github.event_name == 'pull_request' }}
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          name: Types
          working-directory: packages/types
          file-coverage-mode: changes
      - name: Upload backend coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-backend
          path: services/backend/coverage
          if-no-files-found: warn
      - name: Upload types coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-types
          path: packages/types/coverage
          if-no-files-found: warn
